import argparse
import json
import sys

from yt_dlp.cookies import extract_cookies_from_browser


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--browser", required=True)
    parser.add_argument("--profile", default=None)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    try:
        jar = extract_cookies_from_browser(args.browser, args.profile)
        seen = set()
        with open(args.output, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by HP YTdl UI\n")
            for cookie in jar:
                domain = cookie.domain or ""
                domain_flag = "TRUE" if domain.startswith(".") else "FALSE"
                path = cookie.path or "/"
                secure = "TRUE" if cookie.secure else "FALSE"
                expires = str(int(cookie.expires)) if cookie.expires else "0"
                name = cookie.name or ""
                value = cookie.value or ""
                line = "\t".join([domain, domain_flag, path, secure, expires, name, value])
                if line not in seen:
                    f.write(line + "\n")
                    seen.add(line)
        print(json.dumps({"success": True, "count": len(jar)}))
    except Exception as e:
        print(json.dumps({"success": False, "error": str(e)}))
        sys.exit(1)


if __name__ == "__main__":
    main()
