import type { CookiesBody } from "@/types";
import {
  autoDetectCookies,
  cookiesExist,
  deleteCookiesFile,
  inspectCookiesFile,
  signinManager,
  writeCookiesFile,
} from "@/lib/cookies";
import { verifyCookies } from "@/lib/ytdlp";
import {
  AUTH_COOKIE_NAMES,
  CORE_AUTH_COOKIES,
  COOKIES_FILE,
} from "@/config/paths";
import Logger from "@/lib/logger";
import HttpResponse from "@/api/response";

const logger = new Logger("COOKIES");

export const cookiesApi = {
  async GET() {
    const exists = await cookiesExist();
    logger.log(`check exists=${exists}`);
    return HttpResponse.json({ exists, path: COOKIES_FILE });
  },
  async POST(req: Request) {
    const body = (await req.json()) as CookiesBody;
    const lines = (body.content ?? "")
      .split("\n")
      .map((l) => l.replace(/\r$/, ""));
    const ytLines = lines.filter(
      (l) => !l.startsWith("#") && l.includes(".youtube.com"),
    );
    const netscape = [
      "# Netscape HTTP Cookie File",
      "# Generated by HP YTdl UI",
      ...ytLines,
    ];
    const content = netscape.join("\n") + (ytLines.length ? "\n" : "");
    const presentAuth = ytLines
      .filter((l) => {
        const parts = l.split("\t");
        return parts.length >= 7 && AUTH_COOKIE_NAMES.has(parts[5]!);
      })
      .map((l) => l.split("\t")[5]!);
    const missingAuth = [...AUTH_COOKIE_NAMES].filter(
      (n) => !presentAuth.includes(n),
    );
    const hasCore = CORE_AUTH_COOKIES.every((c) => presentAuth.includes(c));
    logger.log(
      `saving ${content.length} chars (${ytLines.length} yt cookies, core=${hasCore})`,
    );
    await writeCookiesFile(content);
    return HttpResponse.json({
      saved: true,
      path: COOKIES_FILE,
      youtube_cookies: ytLines.length,
      missing_auth: missingAuth,
      has_all_auth: hasCore,
    });
  },
  async DELETE() {
    logger.log("deleting");
    await deleteCookiesFile();
    return HttpResponse.json({ deleted: true });
  },
};

export const cookiesDetectApi = {
  async POST() {
    logger.log("auto-detect started");
    const results = await autoDetectCookies();
    logger.log(`auto-detect found=${results.found} total=${results.total} source=${results.source}`);
    return HttpResponse.json(results);
  },
};

export const cookiesInspectApi = async () => {
  const result = await inspectCookiesFile();
  logger.log(`inspect exists=${result.exists} cookies=${result.total_cookies} domains=${result.domains?.length}`);
  return HttpResponse.json(result);
};

export const cookiesVerifyApi = {
  async POST(req: Request) {
    if (!(await cookiesExist())) {
      return HttpResponse.json({ ok: false, needs_signin: false, detail: "No cookies file" });
    }
    let url = "";
    try {
      const body = (await req.json()) as { url?: string };
      url = body.url ?? "";
    } catch {
      /* no body */
    }
    logger.log(`verify started url=${url || "default"}`);
    const result = await verifyCookies(COOKIES_FILE, url || undefined);
    logger.log(`verify ok=${result.ok} needs_signin=${result.needs_signin}`);
    return HttpResponse.json(result);
  },
};

export const cookiesSigninApi = {
  async POST() {
    const status = signinManager.getStatus();
    if (status.inProgress) {
      logger.log("signin already in progress");
      return HttpResponse.json({ status: "already_in_progress" });
    }
    logger.log("signin started");
    signinManager.start();
    return HttpResponse.json({ status: "started" });
  },
};

export const cookiesSigninStatusApi = async () => {
  const status = signinManager.getStatus();
  if (status.done) logger.log(`signin done result=${JSON.stringify(status.result)}`);
  return HttpResponse.json(status);
};

export const cookiesSigninCancelApi = {
  async POST() {
    logger.log("signin cancel requested");
    signinManager.cancel();
    return HttpResponse.json({ status: "cancelled" });
  },
};
