import http.cookiejar
import threading
import time
import webbrowser
from typing import Any

from .config import COOKIES_FILE, get_cookie_browser_targets

try:
    from yt_dlp.cookies import (
        extract_cookies_from_browser,
    )
except Exception:  # noqa: BLE001
    extract_cookies_from_browser: Any = None

_signin_state = {
    "in_progress": False,
    "done": False,
    "result": None,
}

AUTH_COOKIE_NAMES = {"SAPISID", "SSID", "HSID", "SID"}


def _cookiejar_to_netscape_py(cj: http.cookiejar.CookieJar) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by HP YTdl UI"]
    for c in cj:
        if not c.value:
            continue
        include_subs = "TRUE" if c.domain_initial_dot else "FALSE"
        secure = "TRUE" if c.secure else "FALSE"
        if c.expires is None:
            expires = "0"
        else:
            try:
                expires = str(int(c.expires))
            except (TypeError, ValueError):
                expires = "0"
        domain = c.domain or ""
        path = c.path or "/"
        lines.append(f"{domain}\t{include_subs}\t{path}\t{secure}\t{expires}\t{c.name}\t{c.value}")
    return "\r\n".join(lines) + "\r\n"


def _filter_youtube_jar(jar: http.cookiejar.CookieJar) -> http.cookiejar.CookieJar:
    filtered = http.cookiejar.CookieJar()
    for c in jar:
        if "youtube.com" in (c.domain or "") and c.value:
            filtered.set_cookie(c)
    return filtered


# ── Web mode (system browser + polling) ──────────────────────────────

def _start_signin_web() -> None:
    state = _signin_state
    state["in_progress"] = True
    state["done"] = False
    state["result"] = None

    login_url = "https://accounts.google.com/ServiceLogin?continue=https://www.youtube.com&hl=en"
    webbrowser.open(login_url)

    def _poll():
        for _ in range(60):  # 5 min, 5s intervals
            time.sleep(5)
            if not state["in_progress"]:
                return
            if extract_cookies_from_browser is None:
                state["result"] = {"success": False, "error": "yt-dlp cookies API not available"}
                state["done"] = True
                state["in_progress"] = False
                return

            for browser_name, profile in get_cookie_browser_targets():
                try:
                    jar = extract_cookies_from_browser(browser_name, profile=profile)
                except Exception:  # noqa: BLE001,S112
                    continue
                if not jar:
                    continue
                youtube_cookies = [c for c in jar if "youtube.com" in (c.domain or "")]
                if not youtube_cookies:
                    continue
                found_auth = [c.name for c in youtube_cookies if c.name in AUTH_COOKIE_NAMES and c.value]
                if not found_auth:
                    continue

                youtube_jar = _filter_youtube_jar(jar)
                netscape = _cookiejar_to_netscape_py(youtube_jar)
                COOKIES_FILE.parent.mkdir(parents=True, exist_ok=True)
                COOKIES_FILE.write_text(netscape, encoding="utf-8")
                state["result"] = {
                    "success": True,
                    "total": len(youtube_cookies),
                    "youtube_cookies": len(youtube_cookies),
                    "auth_cookies": found_auth,
                    "has_all_auth": all(n in AUTH_COOKIE_NAMES for n in found_auth),
                }
                state["done"] = True
                state["in_progress"] = False
                return

        state["result"] = {
            "success": False,
            "error": "Timed out. Close your browser fully and try again.",
        }
        state["done"] = True
        state["in_progress"] = False

    t = threading.Thread(target=_poll, daemon=True)
    t.start()


# ── Dispatch ─────────────────────────────────────────────────────────

def start_signin() -> None:
    _start_signin_web()


def get_signin_status() -> dict[str, object]:
    s = _signin_state
    return {
        "mode": "web",
        "in_progress": s["in_progress"],
        "done": s["done"],
        "result": s["result"],
    }
