import threading
import time
import webbrowser
from urllib.parse import urlparse

from .config import COOKIES_FILE, get_cookie_browser_targets

try:
    from yt_dlp.cookies import extract_cookies_from_browser  # type: ignore[attr-defined]
except Exception:  # noqa: BLE001
    extract_cookies_from_browser = None  # type: ignore[assignment]

_signin_state = {
    "in_progress": False,
    "done": False,
    "result": None,
    "_window": None,
    "_js_api": None,
}

AUTH_COOKIE_NAMES = {"SAPISID", "SSID", "HSID", "SID"}


def _cookies_to_netscape(cookies: list[dict]) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by HP YTdl UI - WebView Sign-in"]
    seen = set()
    for c in cookies:
        domain = c.get("domain", "")
        name = c.get("name", "")
        value = c.get("value", "")
        if not name or not value:
            continue
        key = (domain, name)
        if key in seen:
            continue
        seen.add(key)
        include_subs = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = str(int(c.get("expires", 0))) if c.get("expires") else "0"
        lines.append(f"{domain}\t{include_subs}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\r\n".join(lines) + "\r\n"


def _save_cookies_from_cookiejar(jar) -> list[str] | None:  # pyright: ignore[reportExplicitAny]
    youtube_cookies = [c for c in jar if "youtube.com" in (c.domain or "")]
    if not youtube_cookies:
        return None
    found_auth = [c.name for c in youtube_cookies if c.name in AUTH_COOKIE_NAMES and c.value]
    import http.cookiejar
    netscape = _cookiejar_to_netscape_py(jar)
    COOKIES_FILE.parent.mkdir(parents=True, exist_ok=True)
    COOKIES_FILE.write_text(netscape, encoding="utf-8")
    return found_auth


def _cookiejar_to_netscape_py(cj) -> str:  # pyright: ignore[reportExplicitAny]
    lines = ["# Netscape HTTP Cookie File", "# Generated by HP YTdl UI"]
    for c in cj:
        if not c.value:
            continue
        include_subs = "TRUE" if c.domain_initial_dot else "FALSE"
        secure = "TRUE" if c.secure else "FALSE"
        if c.expires is None:
            expires = "0"
        else:
            try:
                expires = str(int(c.expires))
            except (TypeError, ValueError):
                expires = "0"
        domain = c.domain or ""
        path = c.path or "/"
        lines.append(f"{domain}\t{include_subs}\t{path}\t{secure}\t{expires}\t{c.name}\t{c.value}")
    return "\r\n".join(lines) + "\r\n"


def _filter_youtube_jar(jar):  # pyright: ignore[reportExplicitAny]
    import http.cookiejar
    filtered = http.cookiejar.CookieJar()
    for c in jar:
        if "youtube.com" in (c.domain or "") and c.value:
            filtered.set_cookie(c)
    return filtered


# ── Desktop mode (pywebview) ──────────────────────────────────────────

class _SignInBridge:
    def extract_cookies(self):
        state = _signin_state
        window = state.get("_window")
        if not window:
            state["result"] = {"success": False, "error": "Window closed"}
            state["done"] = True
            return
        try:
            all_cookies = window.get_cookies("https://www.youtube.com")
            if not all_cookies:
                all_cookies = []
            youtube_cookies = [c for c in all_cookies if "youtube.com" in (c.get("domain", ""))]
            found_auth = [c for c in youtube_cookies if c["name"] in AUTH_COOKIE_NAMES]

            if found_auth:
                netscape = _cookies_to_netscape(youtube_cookies)
                COOKIES_FILE.parent.mkdir(parents=True, exist_ok=True)
                COOKIES_FILE.write_text(netscape, encoding="utf-8")
                auth_names = [c["name"] for c in found_auth]
                state["result"] = {
                    "success": True,
                    "total": len(all_cookies),
                    "youtube_cookies": len(youtube_cookies),
                    "auth_cookies": auth_names,
                    "has_all_auth": all(n in AUTH_COOKIE_NAMES for n in auth_names),
                }
                state["done"] = True
                state["in_progress"] = False
                try:
                    window.destroy()
                except Exception:
                    pass
                return

            state["_extracted"] = False
        except Exception as e:
            state["result"] = {"success": False, "error": str(e)}
            state["done"] = True
            state["in_progress"] = False
            try:
                window.destroy()
            except Exception:
                pass


def _start_signin_desktop() -> None:
    import webview

    state = _signin_state
    state["in_progress"] = True
    state["done"] = False
    state["result"] = None
    state["_extracted"] = False

    js_api = _SignInBridge()
    state["_js_api"] = js_api

    window = webview.create_window(
        "Sign in to YouTube",
        "https://accounts.google.com/ServiceLogin?continue=https://www.youtube.com&hl=en",
        width=950, height=700,
        on_top=True,
        js_api=js_api,
    )
    state["_window"] = window

    def _on_loaded(url: str) -> None:
        if state.get("_extracted"):
            return
        parsed = urlparse(url)
        if parsed.netloc in ("www.youtube.com", "m.youtube.com", "youtube.com"):
            state["_extracted"] = True
            try:
                window.evaluate_js(
                    "setTimeout(function() { window.pywebview.api.extract_cookies(); }, 5000);"
                )
            except Exception:  # noqa: BLE001,S112
                state["_extracted"] = False

    def _on_closed() -> None:
        if not state.get("done"):
            state["result"] = {"success": False, "error": "Sign-in window closed"}
            state["done"] = True
            state["in_progress"] = False

    window.events.loaded += _on_loaded
    window.events.closed += _on_closed


# ── Web mode (system browser + polling) ──────────────────────────────

def _start_signin_web() -> None:
    state = _signin_state
    state["in_progress"] = True
    state["done"] = False
    state["result"] = None

    login_url = "https://accounts.google.com/ServiceLogin?continue=https://www.youtube.com&hl=en"
    webbrowser.open(login_url)

    def _poll():
        for _ in range(60):  # 5 min, 5s intervals
            time.sleep(5)
            if not state["in_progress"]:
                return
            if extract_cookies_from_browser is None:
                state["result"] = {"success": False, "error": "yt-dlp cookies API not available"}
                state["done"] = True
                state["in_progress"] = False
                return

            for browser_name, profile in get_cookie_browser_targets():
                try:
                    jar = extract_cookies_from_browser(browser_name, profile=profile)
                except Exception:  # noqa: BLE001,S112
                    continue
                if not jar:
                    continue
                youtube_cookies = [c for c in jar if "youtube.com" in (c.domain or "")]
                if not youtube_cookies:
                    continue
                found_auth = [c.name for c in youtube_cookies if c.name in AUTH_COOKIE_NAMES and c.value]
                if not found_auth:
                    continue

                youtube_jar = _filter_youtube_jar(jar)
                netscape = _cookiejar_to_netscape_py(youtube_jar)
                COOKIES_FILE.parent.mkdir(parents=True, exist_ok=True)
                COOKIES_FILE.write_text(netscape, encoding="utf-8")
                state["result"] = {
                    "success": True,
                    "total": len(youtube_cookies),
                    "youtube_cookies": len(youtube_cookies),
                    "auth_cookies": found_auth,
                    "has_all_auth": all(n in AUTH_COOKIE_NAMES for n in found_auth),
                }
                state["done"] = True
                state["in_progress"] = False
                return

        state["result"] = {
            "success": False,
            "error": "Timed out. Close your browser fully and try again.",
        }
        state["done"] = True
        state["in_progress"] = False

    t = threading.Thread(target=_poll, daemon=True)
    t.start()


# ── Dispatch ─────────────────────────────────────────────────────────

def start_signin() -> None:
    from .config import APP_MODE  # read fresh each time
    if APP_MODE == "desktop":
        _start_signin_desktop()
    else:
        _start_signin_web()


def get_signin_status() -> dict:
    from .config import APP_MODE  # read fresh each time
    s = _signin_state
    return {
        "mode": APP_MODE,
        "in_progress": s["in_progress"],
        "done": s["done"],
        "result": s["result"],
    }
